In [17]:
import torch
from torch_geometric.datasets import FAUST
#from torch_geometric.transforms import Compose, SamplePoints, Delaunay
import plotly.graph_objects as go
import numpy as np



print(torch.__version__)

root = "D:/LaureaMagistrale/PrimoAnno/Secondo_Semestre/DeepLearning/datasets/MPI-FAUST"

dataset = FAUST(root = root, train=True)

print("Dataset: {}\nLen: {}\nNum Classes: {}\nNum Node features: {}".format(dataset, len(dataset), dataset.num_classes, dataset.num_node_features))

1.12.1+cu116
Dataset: FAUST(80)
Len: 80
Num Classes: 10
Num Node features: 0


In [47]:
dataset[2]

Data(pos=[6890, 3], face=[3, 13776], y=[1])

In [43]:
ix = 2

x = dataset[ix].pos[:,0]
y = dataset[ix].pos[:,1]
z = dataset[ix].pos[:,2]

i = dataset[ix].face[0,:]
j = dataset[ix].face[1,:]
k = dataset[ix].face[2,:]

print(x.shape, y.shape, z.shape)
print(i.shape, j.shape, k.shape)

torch.Size([6890]) torch.Size([6890]) torch.Size([6890])
torch.Size([13776]) torch.Size([13776]) torch.Size([13776])


In [44]:
fig = go.Figure(data=[go.Mesh3d(x = x, y = y, z=z, opacity=0.5, i=i, j=j, k=k)])
fig.show()

In [1]:
import scipy.sparse as sp
import torch 
#import dill
#import pickle
#import torch.nn as nn
#from random import shuffle

#import torch_geometric
#from torch_geometric.loader import DataLoader, DataListLoader

from misc.utils import *
from utils.distances import *
from datasets.faust_2500 import Faust2500Dataset


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

dataset_train = Faust2500Dataset(root="D:\LaureaMagistrale\PrimoAnno\Secondo_Semestre\DeepLearning\datasets\FAUST-2500", train=True)

print(len(dataset_train))

d:\IDEs\anaconda3\envs\AML\lib\site-packages\torch_geometric\deprecation.py:12: UserWarning: 'transforms.RandomTranslate' is deprecated, use 'transforms.RandomJitter' instead
  warnings.warn(out)
Processing...
Done!


Data(y=[80], pos=[168000, 3], faces=[335680, 3], Dg=[168000, 2100], oripos=[168000, 3], idx=[80])
80


In [11]:
ix = 2

x = dataset_train[ix].pos[:,0]
y = dataset_train[ix].pos[:,1]
z = dataset_train[ix].pos[:,2]

i = dataset_train[ix].faces[:,0]
j = dataset_train[ix].faces[:,1]
k = dataset_train[ix].faces[:,2]

print(x.shape, y.shape, z.shape)
print(i.shape, j.shape, k.shape)

fig = go.Figure(data=[go.Mesh3d(x = x, y = y, z=z, opacity=0.5, i=i, j=j, k=k)])
fig.show()

torch.Size([2100]) torch.Size([2100]) torch.Size([2100])
torch.Size([4196]) torch.Size([4196]) torch.Size([4196])


In [6]:
import plotly.express as px

fig = px.scatter_3d(x=x, y=y, z=z)
fig.show()

In [10]:
a = b = c = 100

In [12]:
id(a), id(b), id(c) 

(140720197348192, 140720197348192, 140720197348192)

In [17]:
a += 3

In [19]:
id(a), id(b), id(c)

(140720197345184, 140720197348192, 140720197348192)

In [20]:
a, b, c

(6, 100, 100)

In [21]:
from torch import zeros

In [43]:
loss1 = loss2 = loss3 = loss4 = zeros((1,)).float()

In [44]:
loss1.add_(1.0)

loss1, loss2

(tensor([1.]), tensor([1.]))

In [24]:
loss1, loss2, loss3, loss4

(tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]))

In [29]:
loss1 += 1.
loss1

tensor([5.])

In [30]:
loss1, loss2, loss3, loss4

(tensor([5.]), tensor([5.]), tensor([5.]), tensor([5.]))

In [31]:
loss4 = zeros(1).float()

In [32]:
loss1, loss2, loss3, loss4

(tensor([5.]), tensor([5.]), tensor([5.]), tensor([0.]))

In [45]:
loss1 =  zeros((1,)).float()
loss2 =  zeros((1,)).float()
loss3 =  zeros((1,)).float()
loss4 = zeros((1,)).float()

In [36]:
loss1, loss2, loss3, loss4

(tensor([0.]), tensor([0.]), tensor([0.]), tensor([0.]))

In [46]:
loss1.add_(1.0)

loss1, loss2

(tensor([1.]), tensor([0.]))

In [12]:
"{:.2f}".format(2.0123)

'2.01'

In [56]:
a,b = 0, 1
a

0